// Mock class to prevent errors
// The real client will be generated by OpenAPI TS
class Client {
  private config: {
    baseURL?: string;
    auth?: () => string;
  } = {};

  // setConfig method to match your usage
  setConfig(config: { baseURL?: string; auth?: () => string }) {
    this.config = { ...this.config, ...config };
    return this; // optional: allows chaining
  }

  // Optional: getter to test config at runtime
  getConfig() {
    return this.config;
  }
}

// Export a singleton instance
export const client = new Client();